name: Test release
on:
  release

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo 'release ${{ github.event.release.tag_name }}'
