name: Test release
on:
  release:
    types: [published]

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo 'release'
    - if: contains(github.event.release.tag_name, 'beta')
      run: echo 'waduh, release beta'
    - run: echo 'lanjut'
